# Generated by Django 5.0.2 on 2024-03-29 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0005_remove_news_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.CharField(default='https://res.cloudinary.com/do5keslgr/image/upload/v1711704802/images_rc9qpp.png', max_length=255, null=True),
        ),
    ]
