# Generated by Django 5.0.2 on 2024-05-08 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0006_alter_user_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.RemoveField(
            model_name='user',
            name='topics_selected',
        ),
        migrations.AddField(
            model_name='user',
            name='topics_selected',
            field=models.ManyToManyField(blank=True, to='News.topics'),
        ),
    ]
