# Generated by Django 5.0.2 on 2024-05-10 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0007_alter_share_url_remove_user_topics_selected_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='share',
            name='url',
        ),
    ]
