# Generated by Django 5.0.2 on 2024-05-10 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0008_remove_share_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='news_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='News.newsarticle'),
        ),
    ]
