# Generated by Django 5.0.2 on 2024-07-21 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0010_rename_follower_follow_followers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='followers',
            new_name='follower',
        ),
    ]
